embabel/embabel-agent

README.md
This pull request updates the `README.md` file to fix a broken image link by pointing it to the correct repository and path.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L18-R18): Updated the image source URL to `https://github.com/embabel/embabel-agent/blob/fix-readme/embabel-agent-api/images/315px-Meister_der_Weltenchronik_001.jpg?raw=true` to replace the outdated link and ensure the image displays correctly.
=> Fix path to Embabel Logo

.github/workflows/deploy-snapshots.yml, .github/workflows/maven.yml, embabel-agent-api/pom.xml, embabel-agent-dependencies/pom.xml, embabel-agent-eval/pom.xml, pom.xml
This pull request updates Maven repository configurations across multiple files to transition from using GitHub Packages to Embabel's Artifactory for managing dependencies and snapshots. It also includes some minor structural adjustments in the `pom.xml` files.
* [`.github/workflows/deploy-snapshots.yml`](diffhunk://#diff-441fb097201dd492df86898768fa710e824a03b73403c88c6e4b84404bc76528L24-R24): Updated the Maven server configuration to use `secrets.EMBABEL_ARTIFACTORY` instead of `secrets.GITREPO_WRITE_PACKAGE`.
* [`.github/workflows/maven.yml`](diffhunk://#diff-5dbf1a803ecc13ff945a08ed3eb09149a83615e83f15320550af8e3a91976446L33-L36): Removed the Maven server configuration step that previously referenced `secrets.GITREPO_SERVER`.
* …
=> Artifactory

embabel-agent-api/pom.xml
This pull request removes an unused Maven repository configuration from the `embabel-agent-api/pom.xml` file.
* [`embabel-agent-api/pom.xml`](diffhunk://#diff-c161fccae45bca8f24d2ba5c90f64d55eb224d566485532dbf0d4abf7109d034L230-L243): Deleted the `repositories` section that included the "Central Portal Snapshots" repository, as it is no longer needed.
=> Remove reference to sonatype repository

embabel-agent-api/.mvn/wrapper/maven-wrapper.properties, embabel-agent-api/pom.xml
This pull request updates the Maven wrapper version and removes the `mockk` dependency from the project. Below are the key changes:
* Updated the Maven wrapper version from `3.3.2` to `3.9.6` in `embabel-agent-api/.mvn/wrapper/maven-wrapper.properties` to use a more recent version of Maven.
* Removed the `mockk` version property from `embabel-agent-api/pom.xml` as it is no longer needed.
* Removed the `mockk-jvm` dependency from `embabel-agent-api/pom.xml`, likely as part of a cleanup or migration away from this library.
=> Polishing.

embabel-agent-api/src/main/kotlin/com/embabel/agent/api/dsl/AgentScopeBuilder.kt
This pull request introduces a new function `biAggregate` in the `AgentScopeBuilder` file to handle aggregation with two inputs. The most notable change includes adding a `@Suppress("UNCHECKED_CAST")` annotation to suppress warnings related to unchecked casts.
Key change:
* Added a new function `biAggregate` in `embabel-agent-api/src/main/kotlin/com/embabel/agent/api/dsl/AgentScopeBuilder.kt` to enable aggregation of two inputs using a list of transformations and a merge function. The `@Suppress("UNCHECKED_CAST")` annotation was included to handle unchecked cast warnings.
=> Compiler warning.

embabel-agent-api/src/main/kotlin/com/embabel/agent/api/common/SelfToolCallbackPublisher.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/core/support/springAiUtils.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/toolgroups/web/search/brave/BraveSearchTools.kt, embabel-agent-api/src/test/kotlin/com/embabel/agent/experimental/d/ToolGroupExposerKtTest.kt, embabel-agent-api/src/test/kotlin/com/embabel/agent/spi/support/ChatClientLlmOperationsTest.kt, embabel-agent-api/src/test/kotlin/com/embabel/agent/spi/support/ToolDecoratorsKtTest.kt
This pull request updates the import path for `ToolCallbacks` across multiple files to reflect its relocation from `org.springframework.ai.support` to `org.springframework.ai.tool`. These changes ensure consistency and prevent potential issues caused by outdated imports.
* [`embabel-agent-api/src/main/kotlin/com/embabel/agent/api/common/SelfToolCallbackPublisher.kt`](diffhunk://#diff-e1eaa32858078ebe430893a94231df42bcbb8b778e1841747878da16af6ee6b6L21-R22): Updated the import path for `ToolCallbacks` to `org.springframework.ai.tool.ToolCallbacks`.
* [`embabel-agent-api/src/main/kotlin/com/embabel/agent/core/support/springAiUtils.kt`](diffhunk://#diff-d5a68f3145511ab6db9943d6dd5064d671ee9be83a354caf0848269ac7ec476aL18-R19): Adjusted the import path for `ToolCallbacks` to the new location.
* …
=> Pin Spring AI to version 1.0.0-M4 Issue #290

embabel-agent-api/src/main/kotlin/com/embabel/agent/shell/ShellCommands.kt, embabel-agent-api/src/main/resources/application-shell.yml
This pull request introduces an "exit" command to the `ShellCommands` class, allowing users to gracefully shut down the application. It also includes related changes to support this functionality, such as dependency injection for the application context and configuration updates to disable default exit commands.
* Added a new `exit` method in `ShellCommands` to handle application shutdown. The method logs the shutdown process, clears active processes, and uses `SpringApplication.exit` for a graceful termination. It also provides user feedback and handles exceptions during shutdown. (`embabel-agent-api/src/main/kotlin/com/embabel/agent/shell/ShellCommands.kt`, [embabel-agent-api/src/main/kotlin/com/embabel/agent/shell/ShellCommands.ktR358-R378](diffhunk://#diff-e7d9a3061518898b203311eab7e90 …
=> Issue #307 Agent Shell  hangs under Windows with Docker Desktop Profile

embabel-agent-api/docker-compose.yml, embabel-agent-api/pom.xml, embabel-agent-api/scripts/shell.cmd, embabel-agent-api/scripts/shell.ps1, embabel-agent-api/scripts/shell.sh, embabel-agent-api/scripts/shell_docker.cmd, embabel-agent-api/src/main/kotlin/com/embabel/agent/config/models/OpenAiModels.kt, embabel-agent-api/src/main/resources/application-observability.yml
This pull request introduces observability enhancements to the `embabel-agent-api` project and updates the configuration for model services in the `docker-compose.yml` file. Key changes include adding observability dependencies, enabling observability features in Spring profiles and configurations, and replacing the model service provider setup with a Docker-based configuration.
* **Added dependencies for observability tools**: Included `spring-boot-starter-actuator`, `micrometer-tracing-bridge-brave`, and `zipkin-reporter-brave` in `pom.xml` to enable tracing and metrics collection.
* **Enabled observability in Spring profiles**: Updated `SPRING_PROFILES_ACTIVE` in `shell.cmd`, `shell.ps1`, `shell.sh`, and `shell_docker.cmd` scripts to include the `observability` profile. …
=> Add Support for Micrometer and Zipkin Trace

embabel-agent-api/src/main/resources/application.yml
This pull request includes a small change to the `application.yml` file. It comments out the log level configuration for `org.springframework.context.support.PostProcessorRegistrationDelegate`, effectively disabling the suppression of its error-level logs.
=> Bump up log level to default for PostProcessorRegistrationDelegate.

embabel-agent-api/src/main/kotlin/com/embabel/agent/config/PostProcessBeansListener.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/spi/support/AutoRegistration.kt
This pull request refactors and renames several classes and components related to the agent scanning functionality, aiming to improve clarity and consistency in naming. The most significant changes include renaming `AgentScanningBeanPostProcessor` to `AgentScanningPostProcessorDelegate` and `LazyAgentScanningBeanPostProcessor` to `DelegatingAgentScanningBeanPostProcessor`, along with updates to associated references and logging.
* Renamed `AgentScanningBeanPostProcessor` to `AgentScanningPostProcessorDelegate` across the codebase, including its instantiation, logging, and references in `PostProcessBeansListener` and `AutoRegistration`. [[1]](diffhunk://#diff-4f979d9c7c8807ae469566f58696b5e6c7dda2e542486a9bd18fcbfa8223c611L18-R18) …
=> More descriptive names and more comments.

embabel-agent-api/scripts/shell.cmd, embabel-agent-api/scripts/shell.ps1, embabel-agent-api/scripts/shell.sh, embabel-agent-api/scripts/shell_docker.cmd, embabel-agent-api/src/main/resources/application-observability.yml, embabel-agent-api/src/main/resources/application.yml
This pull request includes updates to configuration files and scripts to refine the application's observability settings and streamline Spring profile management. The most significant changes include removing the "observability" Spring profile from various scripts, modifying observability-related configurations in `application-observability.yml`, and simplifying the `application.yml` file by disabling tracing and removing redundant settings.
* Removed the "observability" Spring profile from the `SPRING_PROFILES_ACTIVE` environment variable in the following scripts: `shell.cmd`, `shell.ps1`, `shell.sh`, and `shell_docker.cmd`. This change ensures that observability settings are no longer applied by default in these scripts. [[1]](diffhunk://#diff-013696b1a8a589dadb335f9b6401bd2c317f21e690de …
=> Issue #403 - Unable to connect to Zipkin during shell startup

embabel-agent-api/src/main/kotlin/com/embabel/agent/api/annotation/actionMethodPromptRunner.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/annotation/support/AgentMetadataReader.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/annotation/support/DefaultActionMethodManager.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/annotation/support/MethodReturnPromptRunner.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/common/OperationContext.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/common/PromptRunner.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/common/support/OperationContextPromptRunner.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/dsl/AgentScopeBuilder.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/dsl/support/promptTransformer.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/spi/LlmOperations.kt, embabel-agent-api/src/test/kotlin/com/embabel/agent/api/common/OperationContextPromptRunnerTest.kt
`PromptRunner` is a higher level API and should not deal with anything lower level than ToolGroups or tool objects. Thus directly exposing Spring AI `ToolCallback` instances is an abstraction leak.
Note that none of the examples were impacted by this.
=> Remove toolCallbacks from PromptRunner

embabel-agent-api/src/main/kotlin/com/embabel/agent/config/models/AnthropicModels.kt
**Overview**
- Adds support for Claude 4 Opus (claude-opus-4-20250514) in AnthropicModels
**Details**
- Registers new @Bean for Claude 4 Opus using the latest model string and Anthropic API
- Sets pricing for Claude 4 Opus per Anthropic documentation:
- Input: $15.00 / 1M tokens
- Output: $75.00 / 1M tokens
- Sets maxTokens = 200,000 and knowledge cutoff to 2025-03-31
- Fallback to GPT-4.1 on error, consistent with other models
**Issues**
- Closes #416
=> Add Claude 4 support #416

embabel-agent-api/pom.xml, embabel-agent-api/src/main/kotlin/com/embabel/agent/config/models/BedrockModels.kt, embabel-agent-api/src/main/resources/application-bedrock.yml
Allow the use of Anthropic LLM models available on AWS Bedrock.
Enabled with 'bedrock' Spring profile.
Only models defined in embabel bloc will be registered in Spring context.
=> Add Bedrock chat models

embabel-agent-api/src/main/kotlin/com/embabel/agent/config/AgentPlatformConfiguration.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/config/models/BedrockModels.kt
This complete PR https://github.com/embabel/embabel-agent/pull/423, bedrock LLMs are created but not available in ModelProvider
Add BedrockModels bean name reference to the @DependsOn annotation of modelProvider in AgentPlatformConfiguration
Sorry for the missing change
=> Ensure bedrock models are injected into ModelProvider

embabel-agent-api/src/test/kotlin/com/embabel/agent/support/LlmInvocationHistoryTest.kt
Running mvn test leads to failing tests with when writing price with a '.', some locale uses ','.
This fix (issue #433) removes hardcoded '.' and also use the default locale in test, matching the default locale usage in code
=> Fix issue 433 price formatting locale in test

pom.xml
This pull request updates the Maven build configuration in the `pom.xml` file to include additional plugins for enhanced functionality.
Build configuration updates:
* [`pom.xml`](diffhunk://#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R108-R115): Added the `build-helper-maven-plugin` and `maven-source-plugin` to the `<plugins>` section to support advanced build tasks and source code packaging.
=> Add managed plugins to generate Kotlin and Java sources.jar.

embabel-agent-api/src/main/kotlin/com/embabel/agent/mcpserver/McpServerConfiguration.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/spi/support/AutoRegistration.kt
This pull request introduces event-driven synchronization to ensure proper initialization of tool callbacks in the MCP server and adds support for bean lifecycle management. It also introduces a new custom event to signal the completion of agent scanning. These changes improve the reliability and maintainability of the MCP server configuration and agent scanning processes.
* Replaced direct injection of `McpToolExportCallbackPublisher` with dynamic retrieval from the `applicationContext`, ensuring all tool callbacks are registered after application initialization. (`embabel-agent-api/src/main/kotlin/com/embabel/agent/mcpserver/McpServerConfiguration.kt`, [embabel-agent-api/src/main/kotlin/com/embabel/agent/mcpserver/McpServerConfiguration.ktL41-R62](diffhunk://#diff-852afcc750a601c89ed8820 …
=> Issue #450

embabel-agent-api/src/main/kotlin/com/embabel/agent/mcpserver/McpServerConfiguration.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/spi/support/AutoRegistration.kt
This pull request introduces enhancements to the MCP server configuration by adding a new banner tool and simplifying the tool callback registration process. It also removes unused imports and redundant code for bean refreshing, streamlining the codebase.
* Added a new `BannerTool` class to display a welcome banner with server and Java runtime information. This tool is integrated into the MCP server as a callback provider. (`embabel-agent-api/src/main/kotlin/com/embabel/agent/mcpserver/McpServerConfiguration.kt`, [[1]](diffhunk://#diff-852afcc750a601c89ed8820142c1efa08c0746d843e3e829eca96573c6b151ffR42-R65) [[2]](diffhunk://#diff-852afcc750a601c89ed8820142c1efa08c0746d843e3e829eca96573c6b151ffR76-R86)
* Simplified the tool callback registration process by removing the `refreshBean` method …
=> Fix Agent Tools Discovery - Issue #450

pom.xml
This pull request modifies the `pom.xml` file to adjust how the `embabel-agent-docs` module is handled. The module is removed from the main list of modules and instead added under a new Maven profile, which is inactive by default. This change allows for more flexible builds where the documentation module can be included only when explicitly activated.
Changes to module handling:
* [`pom.xml`](diffhunk://#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L24): Removed `embabel-agent-docs` from the main `<modules>` section.
* [`pom.xml`](diffhunk://#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R118-R130): Added a new Maven profile for `embabel-agent-docs`, inactive by default, enabling selective inclusion during builds.
=> Create dedicated maven profile to build docs.

.github/workflows/deploy-docs.yml, .github/workflows/maven.yml
This pull request introduces a new GitHub Actions workflow for deploying documentation to a virtual machine and removes redundant steps from an existing Maven build workflow. The changes streamline the build process and enable automated deployment of generated documentation.
* [`.github/workflows/deploy-docs.yml`](diffhunk://#diff-87e860af4b9db6c503ed680b6edb6333c6f8d7659f7d1a779a2487466bbc50f6R1-R86): Added a new workflow named "Publish Docs" that builds documentation using Maven and deploys it to a specified VM instance. The workflow includes steps for setting up Java, installing Graphviz for PlantUML diagrams, authenticating with Google Cloud, and deploying files to the VM. It supports manual triggering with configurable inputs for environment, VM instance name, and zone.
* …
=> GitHub Action to publish Docs.

.github/workflows/deploy-docs.yml
This pull request updates the deployment process in the `.github/workflows/deploy-docs.yml` file to improve file transfer and permissions handling during deployment to a virtual machine (VM). The most significant change is the addition of a two-step process that uses `sudo` to ensure proper file placement and permissions.
Deployment process improvements:
* Changed the deployment step name to "Deploy to VM with sudo" for clarity.
* Updated the file transfer process to first copy files to the user's home directory and then move them to the target directory using `sudo` via SSH. This ensures proper permissions and ownership for the deployed files.
=> Fix Publish Docs Action

embabel-agent-api/src/main/kotlin/com/embabel/agent/api/annotation/support/AgentMetadataReader.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/common/support/BranchingAction.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/dsl/AgentScopeBuilder.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/core/support/SerializableAction.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/event/logging/personality/colossus/ColossusLoggingAgenticEventListener.kt, embabel-agent-api/src/test/kotlin/com/embabel/agent/api/annotation/support/AgentMetadataReaderGoalsTest.kt, embabel-agent-api/src/test/kotlin/com/embabel/agent/api/annotation/support/testTypes.kt, embabel-agent-docs/src/main/asciidoc/reference/annotations.adoc, embabel-agent-examples/examples-kotlin/movie/src/main/kotlin/com/embabel/example/movie/MovieFinder.kt
Simplify Action and Condition methods in annotation model to take only `OperationContext`.
=> API cleaning

embabel-agent-api/src/main/kotlin/com/embabel/agent/a2a/server/A2ARequestHandler.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/a2a/server/support/A2AEndpointRegistrar.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/a2a/server/support/A2AStreamingHandler.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/a2a/server/support/AutonomyA2ARequestHandler.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/a2a/spec/a2a.kt
feature(a2a): Implement real-time streaming for agent responses
This PR implements streaming support for the A2A protocol using Server-Sent Events (SSE)
- Add streaming support for message/stream endpoint using Server-Sent Events (SSE)
- Implement A2AStreamingHandler to manage SSE connections and events
- Add streaming event types for messages, tasks, and status updates
- Handle streaming lifecycle, including connection, events, and cleanup
- Support error handling and graceful stream termination
- Add proper content type handling for streaming responses
- Uses Spring's SseEmitter for SSE implementation
- Implements proper stream lifecycle management with connection tracking
- Handles various event types (messages, tasks, status updates)
- Includes comprehensive error handling and cleanup …
=> A2A: Implement message/stream endpoint:

embabel-agent-dependencies/pom.xml, embabel-agent-starters/embabel-agent-starter/pom.xml
This pull request includes updates to the Maven configuration files to correct artifact references and refine packaging details. These changes ensure consistency and proper dependency management across the project.
Dependency and artifact corrections:
* [`embabel-agent-dependencies/pom.xml`](diffhunk://#diff-afe07651950d7d2835eb6cc02163f9241976a101f42ab11fe2d932fc246750f9L53-R53): Updated the artifact ID from `embabel-agent-starters` to `embabel-agent-starter` to fix a naming inconsistency.
Packaging refinement:
* [`embabel-agent-starters/embabel-agent-starter/pom.xml`](diffhunk://#diff-12b13ec3361f83bd85031fac40992f1bd1d47266de643cd40084b14f623d159fL11): Removed the `<packaging>` element, which previously specified `pom`, as it is no longer needed for this module.
=> Make embabel-starter a JAR depenency

embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/EnableAgentMcp.java
This pull request includes a renaming and update to the `EnableAgentMCP` annotation. The changes improve clarity and modify the default agent configuration.
Annotation updates:
* [`embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/EnableAgentMcp.java`](diffhunk://#diff-2204808d8408e4664e6c10c4e0bd87c8429f4d8537e6ba3ff6b12897223c3b5fL24-R29): Renamed the file and class from `EnableAgentMCP` to `EnableAgentMcp` to follow consistent naming conventions. Updated the annotation's description from "Enable MVP Profiles" to "Enable MCP Profiles" and changed the default agents from `"docker-desktop, docker-ce"` to `"docker-desktop, web"`.
=> Consistent Naming Conventions with Spring AI

embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/EnableAgentMcp.java, embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/EnableAgentShell.java, embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/spi/EmbabelEnvironmentProcessor.java, embabel-agent-autoconfigure/src/test/java/com/embabel/agent/config/annotation/LoggingThemeParameterizedTest.java, embabel-agent-autoconfigure/src/test/java/com/embabel/agent/config/annotation/spi/EmbabelEnvironmentProcessorTest.java
This pull request enhances the `EmbabelEnvironmentProcessor` to support logging themes in `@EnableAgentShell` and `@EnableAgentMcp` annotations, processes these themes into Spring profiles, and introduces comprehensive test coverage for edge cases. The most important changes include adding the `loggingTheme` attribute, modifying the environment processor to handle this attribute, and implementing extensive test cases.
* Added a `loggingTheme` attribute to the `@EnableAgentShell` and `@EnableAgentMcp` annotations, with a default value of `"severence"`. This allows specifying an optional logging theme for agents. [[1]](diffhunk://#diff-2204808d8408e4664e6c10c4e0bd87c8429f4d8537e6ba3ff6b12897223c3b5fR30-R34) [[2]](diffhunk://#diff-153cb4756da0ee6ba9da93d0d72ec318405b7538760eed243d2b36103a5a98 …
=> Add loggingTheme support.

embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/EnableAgentMcp.java, embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/EnableAgentShell.java
This pull request makes minor updates to the `EnableAgentMcp` and `EnableAgentShell` annotations by changing the default logging theme and updating the enabled agents for `EnableAgentMcp`.
Annotation updates:
* [`EnableAgentMcp`](diffhunk://#diff-2204808d8408e4664e6c10c4e0bd87c8429f4d8537e6ba3ff6b12897223c3b5fL28-R34): Updated the enabled agents from `"docker-desktop, web"` to `"mcp-server"` and corrected the default logging theme from `"severence"` to `"severance"`. (`embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/EnableAgentMcp.java`, [embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/EnableAgentMcp.javaL28-R34](diffhunk://#diff-2204808d8408e4664e6c10c4e0bd87c8429f4d8537e6ba3ff6b12897223c3b5fL28-R34))
* …
=> Remove docker-desktop from @EnableAgentMcp

embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/EnableAgentMcp.java, embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/LoggingTheme.java, embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/spi/EmbabelEnvironmentProcessor.java, embabel-agent-autoconfigure/src/test/java/com/embabel/agent/config/annotation/LoggingThemeParameterizedTest.java, embabel-agent-autoconfigure/src/test/java/com/embabel/agent/config/annotation/spi/EmbabelEnvironmentProcessorTest.java
This pull request introduces a new `LoggingTheme` enum to standardize logging theme values across the codebase, replacing string-based themes. It updates annotations, processing logic, and tests to use this enum. Additionally, redundant test cases for invalid or unknown themes have been removed. 
* Introduced a new `LoggingTheme` enum with predefined values `SEVERANCE` and `STARWARS`. This replaces string-based themes for better type safety and consistency. (`embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/LoggingTheme.java`)
* Updated the `loggingTheme` attribute in `@EnableAgentMcp` and `@EnableAgentShell` annotations to use the `LoggingTheme` enum instead of strings. (`EnableAgentMcp.java` [[1]](diffhunk://#diff-2204808d8408e4664e6c10c4e0bd87c8429f4d8537e6b …
=> Add LoggingTheme Enum.

embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/LoggingTheme.java, embabel-agent-autoconfigure/src/test/java/com/embabel/agent/config/annotation/LoggingThemeParameterizedTest.java, embabel-agent-autoconfigure/src/test/java/com/embabel/agent/config/annotation/spi/EmbabelEnvironmentProcessorTest.java
This pull request standardizes the naming convention for the `LoggingTheme` enum by changing `STARWARS` to `STAR_WARS` and updates all related test cases accordingly.
* Renamed `STARWARS` to `STAR_WARS` in the `LoggingTheme` enum to align with consistent naming conventions. (`embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/LoggingTheme.java`)
* Updated test cases in `LoggingThemeParameterizedTest` to use the renamed `LoggingTheme.STAR_WARS`:
- Modified `testEnableAgentShellAlone` method. (`embabel-agent-autoconfigure/src/test/java/com/embabel/agent/config/annotation/LoggingThemeParameterizedTest.java`)
- Modified `testEnableAgentsEmptyArray` method. (`embabel-agent-autoconfigure/src/test/java/com/embabel/agent/config/annotation/LoggingThemeParameterizedTest.ja …
=> Polishing LoggingTheme Enum

embabel-agent-autoconfigure/README.md, embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/AgentPlatform.java, embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/EnableAgentMcpServer.java, embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/EnableAgentShell.java, embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/EnableAgents.java, embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/StartupMode.java, embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/spi/EmbabelEnvironmentPostProcessor.java, embabel-agent-autoconfigure/src/test/java/com/embabel/agent/config/annotation/EnableAgentsAnnotationIT.java, embabel-agent-autoconfigure/src/test/java/com/embabel/agent/config/annotation/spi/EmbabelEnvironmentPostProcessorTest.java
This pull request introduces several updates to the `embabel-agent-autoconfigure` module, focusing on refactoring annotations, improving profile management, and enhancing test coverage. The changes include replacing hardcoded strings with constants, introducing a new `StartupMode` class, and updating tests to reflect these modifications.
* Introduced a new `StartupMode` class to define constants for profile names like `SHELL` and `MCP_SERVER`, replacing hardcoded string values in annotations such as `@EnableAgentShell` and `@EnableAgentMcpServer` (`embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/StartupMode.java`, [embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/StartupMode.javaR1-R24](diffhunk://#diff-0dc8783bc38276c90c40098969ae …
=> Fixes related to Agent startup and auto configuration.

embabel-agent-api/src/main/kotlin/com/embabel/agent/config/models/AnthropicModels.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/config/models/OpenAiModels.kt
Due to restricted access to the official `OpenAI` and `Anthropic` APIs in certain regions, users often rely on proxy endpoints for connectivity. This commit adds support for custom baseUrl configuration, providing greater flexibility and ease of use in such environments.
=> Support custom baseUrl for OpenAI and Anthropic APIs

.gitignore, flake.lock, flake.nix
This pull request introduces a new `flake.nix` file to set up a Nix-based development environment for the Embabel Agent Framework. The file defines dependencies, build processes, and development shells tailored for different use cases, such as general development, CI/CD, and documentation.
* Added a `flake.nix` file that describes the project, specifies dependencies (`nixpkgs`, `flake-utils`), and defines outputs for building and developing the project.
* Configured the build process for the Embabel Agent Framework using `maven` and `jdk21`. The project is packaged into a JAR file, and a wrapper script is created for running the application.
* Defined a default development shell with tools for Java/Kotlin development, database testing, container management, and IDE support. Includes a …
=> Add flake.nix dev env

embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/spi/EnvironmentPostProcessor.java, embabel-agent-autoconfigure/src/test/java/com/embabel/agent/config/annotation/spi/EnvironmentPostProcessorTest.java
This pull request refactors the `EnvironmentPostProcessor` to remove reliance on the `spring.profiles.active` system property and instead directly updates the Spring environment with active profiles. It also updates the corresponding tests to align with the new behavior.
* Updated `EnvironmentPostProcessor` to use `environment.addActiveProfile` for managing active profiles instead of modifying the `spring.profiles.active` system property. This ensures profiles are added directly to the Spring environment. (`embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/spi/EnvironmentPostProcessor.java`, [embabel-agent-autoconfigure/src/main/java/com/embabel/agent/config/annotation/spi/EnvironmentPostProcessor.javaL239-R247](diffhunk://#diff-4eb99aeedef78d221ee777dcfd8e6b915 …
=> Issue-546 SPRING_ACTIVE_PROFILE was not getting added to the Environment

.idea/compiler.xml, .idea/encodings.xml, embabel-agent-api/pom.xml, embabel-agent-api/src/main/kotlin/com/embabel/agent/config/models/BedrockModels.kt, embabel-agent-api/src/main/resources/application-bedrock.yml, embabel-agent-api/src/test/kotlin/com/embabel/agent/config/models/BedrockModelsIntegrationTest.kt, embabel-agent-dependencies/pom.xml, embabel-agent-starters/embabel-agent-starter-bedrock/pom.xml, embabel-agent-starters/pom.xml
This PR adds a embabel-agent-starter for Bedrock, to avoid non-bedrock users to depends on useless libraries.
This also adds bedrock embedding models (Titan, Cohere) using enums from spring-ai-bedrock :
- COHERE_EMBED_MULTILINGUAL_V3("cohere.embed-multilingual-v3")
- COHERE_EMBED_ENGLISH_V3("cohere.embed-english-v3")
- TITAN_EMBED_IMAGE_V1("amazon.titan-embed-image-v1")
- TITAN_EMBED_TEXT_V1("amazon.titan-embed-text-v1")
- TITAN_EMBED_TEXT_V2("amazon.titan-embed-text-v2:0")
=> Bedrock starter

embabel-agent-dependencies/pom.xml, embabel-agent-mcpserver/pom.xml, embabel-agent-mcpserver/src/main/kotlin/com/embabel/agent/mcpserver/McpServerConfiguration.kt, embabel-agent-mcpserver/src/main/kotlin/com/embabel/agent/mcpserver/PerGoalToolCallbackProvider.kt, embabel-agent-mcpserver/src/test/kotlin/com/embabel/agent/mcpserver/PerGoalToolCallbackProviderTest.kt, embabel-agent-test/pom.xml, embabel-agent-test/src/main/kotlin/com/embabel/agent/test/domain/gardenOfEden.kt, embabel-agent-test/src/main/kotlin/com/embabel/agent/test/domain/simplyMagic.kt, embabel-agent-test/src/main/kotlin/com/embabel/agent/test/dsl/agentBuilderUtils.kt, embabel-agent-test/src/main/kotlin/com/embabel/agent/test/dsl/dslAgents.kt, embabel-agent-test/src/main/kotlin/com/embabel/agent/test/type/testTypes.kt
This pull request introduces the `embabel-agent-mcpserver` module, which provides functionality for exposing tools via an MCP (Model Context Protocol) server. It includes the addition of dependencies, configuration for tool callbacks, and testing utilities. Below is a summary of the most significant changes grouped by theme.
* **Module Addition**: Added a new Maven module `embabel-agent-mcpserver` with its own `pom.xml`, dependencies, and build plugins. This module is responsible for discovering and exporting tools as MCP server functionalities. (`embabel-agent-mcpserver/pom.xml`)
* **MCP Server Configuration**: Introduced `McpServerConfiguration`, which configures the MCP server to expose tools like a welcome banner and registers tool callbacks dynamically after agent scanning completes. …
=> Add embabel-agent-mcpserver module.

embabel-agent-a2a/pom.xml, embabel-agent-a2a/src/main/kotlin/com/embabel/agent/a2a/.gitkeep, embabel-agent-a2a/src/main/resources/.gitkeep, embabel-agent-a2a/src/tests/kotlin/com/embabel/agent/a2a/.gitkeep, embabel-agent-a2a/src/tests/resources/.gitkeep, embabel-agent-ux/pom.xml, embabel-agent-ux/src/main/kotlin/com/embabel/agent/ux/.gitkeep, embabel-agent-ux/src/main/resources/.gitkeep, embabel-agent-ux/src/tests/kotlin/com/embabel/agent/ux/.gitkeep, embabel-agent-ux/src/tests/resources/.gitkeep
This pull request introduces two new Maven modules, `embabel-agent-a2a` and `embabel-agent-ux`, along with their respective project structures. The most significant changes include the addition of `pom.xml` files for both modules and the creation of `.gitkeep` files to establish the directory structure.
* [`embabel-agent-a2a/pom.xml`](diffhunk://#diff-d6cba7ad69a2b8311836cc61ca5b1d7a6c8ede204b236d165134938974b17ab6R1-R44): Added a `pom.xml` file to define the `embabel-agent-a2a` module, including dependencies (`embabel-agent-api`, `embabel-agent-test`) and build plugins (`kotlin-maven-plugin`, `maven-surefire-plugin`).
* [`embabel-agent-ux/pom.xml`](diffhunk://#diff-b26615d698adf4c5a1bf7cfb2fd6fad10e2cb4aa350c0a27c8c54b30f30b574dR1-R44): Added a `pom.xml` file to define the …
=> Add embabel-agent-ux and embabel-agent-a2a modules.

embabel-agent-api/pom.xml, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/common/support/SelfToolCallbackPublisher.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/config/models/BedrockModels.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/core/support/springAiUtils.kt, embabel-agent-api/src/test/kotlin/com/embabel/agent/experimental/d/ToolGroupExposerKtTest.kt, embabel-agent-api/src/test/kotlin/com/embabel/agent/spi/support/ChatClientLlmOperationsTest.kt, embabel-agent-api/src/test/kotlin/com/embabel/agent/spi/support/ToolDecoratorsKtTest.kt, embabel-agent-eval/pom.xml
This pull request introduces dependency updates and code adjustments to integrate the `spring-ai-client-chat` library and refactor imports for `ToolCallbacks`. Additionally, it includes a minor change to the `BedrockModels` configuration to support observation registries.
* Added the `spring-ai-client-chat` dependency to `embabel-agent-api/pom.xml` and `embabel-agent-eval/pom.xml` to enable chat client functionality. [[1]](diffhunk://#diff-c161fccae45bca8f24d2ba5c90f64d55eb224d566485532dbf0d4abf7109d034R109-R113) [[2]](diffhunk://#diff-2b64a4488eca14ff91f45c005ca5190d872ccafe459b02ae442ae47b83d4a2bfR27-R31)
* Updated import statements across multiple files to use `org.springframework.ai.support.ToolCallbacks` instead of `org.springframework.ai.tool.ToolCallbacks`. This change aligns with …
=> Upgrade to Spring AI 1.0.0

embabel-agent-api/src/main/kotlin/com/embabel/agent/api/common/autonomy/AgentProcessExecution.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/common/autonomy/Autonomy.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/common/support/MultiTransformationAction.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/common/support/TransformationAction.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/core/hitl/Awaitable.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/core/hitl/ConfirmationRequest.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/core/hitl/FormBindingRequest.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/spi/LlmOperations.kt, embabel-agent-api/src/main/kotlin/com/embabel/plan/goap/OptimizingGoapPlanner.kt, embabel-agent-api/src/test/kotlin/com/embabel/agent/core/hitl/FormBindingRequestTest.kt, embabel-agent-mcpserver/src/main/kotlin/com/embabel/agent/mcpserver/McpSyncServerConfiguration.kt, embabel-agent-mcpserver/src/main/kotlin/com/embabel/agent/mcpserver/support/PerGoalToolCallbackProvider.kt, embabel-agent-mcpserver/src/test/kotlin/com/embabel/agent/mcpserver/PerGoalToolCallbackProviderTest.kt, embabel-agent-shell/src/main/kotlin/com/embabel/agent/shell/ShellCommands.kt, embabel-agent-shell/src/main/kotlin/com/embabel/agent/shell/TerminalServices.kt, embabel-agent-shell/src/main/kotlin/com/embabel/chat/agent/shell/LastMessageIntentAgentPlatformChatSession.kt
Also 
- Works around a bug in planner pruning
- Improves logging of `Autonomy` operations
- Improves `Action` implementations `toString` methods for clarity
- Simplifies use of `LlmOperations`
- Changes form binding signatures to use `AgentProcess` instead of `ProcessContext`
=> Start of HITL support for MCP

README.md, embabel-agent-api/src/main/resources/application-docker-desktop.yml
docker mcp gateway run is still the right default config
The issue we were seeing was a bug in Docker Desktop.  The issue is fixed in Docker version 4.43.2
=> revert change to mcp gateway config

embabel-agent-api/src/main/resources/application.yml
This pull request introduces a small but important configuration update to the logging settings in the `application.yml` file. The change suppresses warnings from AWS Bedrock and the AWS SDK by setting their logging levels to `ERROR`, ensuring cleaner logs until an autoconfiguration issue is resolved.
=> Supress AWS Warning. Need to revisit AutoConfiguration seutp.

embabel-agent-api/src/main/kotlin/com/embabel/agent/api/annotation/support/AgentMetadataReader.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/validation/GoapPathToCompletionValidator.kt
###Description
This PR fixes a bug (#449) that caused some agents to fail validation with a `NO_STARTING_ACTION` error. The issue stemmed from the `GoapPathToCompletionValidator`, which, under certain conditions, failed to identify valid starting actions and build a correct initial world state for the planner.
In addition to the bug fix, this PR introduces a structural improvement by refactoring the `AgentMetadataReader` to use constructor-based dependency injection for its validators, enhancing clarity and testability.
---
The `GoapPathToCompletionValidator` failed to get the first actions and create a correct initial world state under special conditions for the agent. It didn't account for external inputs, leading to behavior where all actions depended on the outputs of other actions, …
=> fix(validation): Resolve NO_STARTING_ACTION error and refactor validations

embabel-agent-api/pom.xml, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/common/autonomy/AgentInvocation.kt, embabel-agent-api/src/test/java/com/embabel/agent/api/common/autonomy/AgentInvocationJavaTest.java, embabel-agent-api/src/test/kotlin/com/embabel/agent/api/common/autonomy/AgentInvocationKotlinTest.kt
This PR resolves #592, and introduces the AgentInvocation type, a convenient wrapper around AgentPlatform, meant to provide a user-friendly an alternative to directly using AgentPlatform.
This PR is a draft, because one TODO remains: implementing `AgentPlatform::findAgentByResultType`.
=> Introduce AgentInvocation

embabel-agent-test/pom.xml
This pull request adds a new dependency to the `embabel-agent-test/pom.xml` file to support mocking in tests.
Testing improvements:
* Added the `mockito-core` dependency with compile scope to enable mocking capabilities for unit tests.
=> Add managed Mockito dependency with compile scope.

.gitignore, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/annotation/support/AgentMetadataReader.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/annotation/support/DefaultActionMethodManager.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/annotation/support/DuplicateParameterType.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/annotation/support/DuplicateParameterTypeException.kt, embabel-agent-api/src/test/kotlin/com/embabel/agent/api/annotation/support/RequireNonAmbiguousParametersTest.kt
This pull request introduces validation checks to handle cases where an @Action or @Condition has multiple parameters of the same type. To ensure accurate value binding in such scenarios, developers must now annotate the parameters with @RequireNameMatch. This annotation explicitly instructs the system on how to correctly map the parameter values.
- Added validation logic to detect multiple parameters of the same type in @Action and @Condition.
- Enforced usage of @RequireNameMatch for proper parameter binding.
This change prevents ambiguous parameter binding and avoiding unexpected behavior when parameters have the same class type.
- Added unit tests to verify validation behavior for single and multiple parameters.
- Tested edge cases where @RequireNameMatch is omitted or incorrectly …
=> Add Validation for Multiple Parameters of Same Type in @Action and @Condition

embabel-agent-docs/src/main/resources/themes/embabel-agent-docs.css
* boolean literals, types in front of a method (eg Foo::bar) and a few other items are properly visible in code samples
* Footnotes are not black-on-black
* Admonition blocks look ok. In the end I didn't use font-awesome, I brought back the defaults, but tweaked colors so they work. 
* Quotes look ok enough. 
* Removed rounded corners on TOC - they didn't work. 
This to me is acceptable. 
* Grab the BG from the website and stick it under the content with an opaque effect, so it looks the same as the site
* Grab the header from the website and pull it in - the SVG logo, the Embabel font, and the button that links to github. 
* Get tabs working in code samples.
=> More doc fixes.

embabel-agent-api/src/main/kotlin/com/embabel/agent/core/ProcessOptions.kt, embabel-agent-api/src/test/java/com/embabel/agent/core/ProcessOptionsBuilderTest.java
This commit introduces builder options for ProcessOptions fields introduced since the builder's introduction.
See #659
=> Update ProcessOptions builder to handle new fields

.github/workflows/maven.yml
This pull request updates the `.github/workflows/maven.yml` workflow to better handle builds from public forks and improve CI security and reliability. The main change is the introduction of a separate job for pull requests originating from forks, which avoids running SonarCloud analysis for those builds.
**Workflow improvements:**
* Added a conditional to the main `build` job so it only runs for pushes and pull requests from the same repository, preventing SonarCloud analysis from running on forked pull requests.
* Introduced a new `build-fork` job that runs for pull requests from public forks. This job sets up the environment, builds, and tests the code, but skips SonarCloud analysis to avoid exposing secrets or exceeding usage limits.
=> Update GitHub Actions workflow for conditional builds

embabel-agent-api/src/main/kotlin/com/embabel/agent/api/annotation/support/AgentMetadataReader.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/annotation/support/DefaultActionMethodManager.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/annotation/support/utils.kt, embabel-agent-api/src/test/kotlin/com/embabel/agent/api/annotation/support/RequireNonAmbiguousParametersTest.kt
This PR changes the `DefaultActionMethodManager` so that it only uses the Kotlin reflection API when available, and falls back to the Java reflection API when it is not. Before this PR, methods were invoked using both Java and Kotlin reflection.
Furthermore, this commit throws an exception when code is compiled without the -java-parameters or -parameters flag (see #728).
=> Use java reflection when kotlin-reflect is unavailable

README.md
* We have it as a badge
* However it easy easy to scroll right past and doesn't have the word 'discord'. 
Since community engagement is important, let's feature it one more time at the bottom, and call-out why it is a good idea to join.
=> Prominently feature discord link.

embabel-agent-docs/pom.xml
This pull request makes a minor update to the `pom.xml` file for the `embabel-agent-docs` module. The change removes a redundant or outdated source directory reference for `embabel-agent-autoconfigure`, likely to prevent duplicate or incorrect source inclusion.
* Removed the `<dir>${project.parent.basedir}/embabel-agent-autoconfigure/src/main/java</dir>` entry from the list of source directories in `embabel-agent-docs/pom.xml`.
=> Remove embabel-agent-autoconfigure from dokka docs build.

embabel-agent-api/src/main/resources/application-docker-ce.yml, embabel-agent-autoconfigure/embabel-agent-platform-autoconfigure/src/main/java/com/embabel/agent/config/annotation/McpServers.java
Merged PR #803 contributed by https://github.com/npiv and approved by @slimslenderslacks 
This pull request updates the configuration and constants for Docker environments, specifically standardizing the naming convention for Docker Community Edition (CE) and updating related environment variables.
Configuration updates:
* Changed the constant `DOCKER` to `docker-ce` in `McpServers`, ensuring consistency with Docker CE naming throughout the codebase.
Environment variable improvements:
* Updated the Docker command configuration in `application-docker-ce.yml` to include the `BRAVE_MCP_TRANSPORT` environment variable with a value of `"stdio"`, ensuring the correct transport is set for Brave MCP.
=> Fix Brave MCP

embabel-agent-api/src/main/kotlin/com/embabel/agent/api/annotation/support/ActionMethodArgumentResolver.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/api/annotation/support/DefaultActionMethodManager.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/core/Blackboard.kt, embabel-agent-api/src/test/kotlin/com/embabel/agent/api/annotation/support/ActionMethodArgumentResolverTest.kt, embabel-agent-api/src/test/kotlin/com/embabel/agent/api/annotation/support/AgentMetadataReaderActionTest.kt
This commit introduces the ActionMethodArgumentResolver, a strategy interface used by the DefaultActionMethodManager to delegate action method resolution to.
This commit introduces `Blackboard::hasValue`, used by the `BlackBoardArgumentResolver` to determine whether a argument can be resolved.
See gh-575
=> Introduce custom argument resolvers

embabel-agent-api/src/main/kotlin/com/embabel/agent/api/annotation/support/AgentMetadataReader.kt
API  ClassUtils.isCglibProxyClass(clazz)  gets deprecated.
Replaced with new API:
```
org.springframework.cglib.proxy.Enhancer.isEnhanced(clazz)
```
=> Replace deprecated API ClassUtils isCglibProxy

.github/workflows/deploy-snapshots.yml
This pull request makes a minor update to the deployment workflow. The Maven deploy command in `.github/workflows/deploy-snapshots.yml` now includes the `clean` phase to ensure the build directory is cleared before deployment.
=> Change Maven command to include 'clean' step

.github/workflows/deploy-snapshots.yml
This pull request makes a minor update to the Maven deployment command in the GitHub Actions workflow. The order of the `mvn` command arguments has been adjusted for consistency with standard Maven practices.
=> Reorder Maven command for deployment

.github/scripts/dependabot-group-alerts.sh, .github/workflows/dependabot-insights.yml
https://github.com/embabel/embabel-agent/issues/850
Dependabot Vulnerability report comes with duplicate entries per  module (pom).  
Its time consuming to group entries by jar (artifact) and go over all related pages.
Automated vulnerability report generation with proper grouping.
```
org.apache.tomcat.embed:tomcat-embed-core — GHSA-3p2h-wqq4-wf4h (1 unique alerts)
Affected modules:
- embabel-agent-mcpserver/pom.xml
- embabel-agent-starters/embabel-agent-starter-mcpserver/pom.xml
- Severity: medium | Apache Tomcat Denial of Service via invalid HTTP priority header
↪ Recommendation: Upgrade org.apache.tomcat.embed:tomcat-embed-core to a safe version (see advisory below)
↪ Advisory URL: https://github.com/advisories/GHSA-3p2h-wqq4-wf4h
```
Added vulnerability report generation to workflow …
=> Generate Dependabot Vulnerability Summary Report

.github/scripts/dependabot-group-alerts.sh, .github/workflows/dependabot-insights.yml
https://github.com/embabel/embabel-agent/issues/850
Dependabot Vulnerability report comes with duplicate entries per  module (pom).  
Its time consuming to group entries by jar (artifact) and go over all related pages.
Automated vulnerability report generation with proper grouping.
```🔐 org.apache.tomcat.embed:tomcat-embed-core — GHSA-3p2h-wqq4-wf4h (1 unique alerts)
Affected modules:
- embabel-agent-mcpserver/pom.xml
- embabel-agent-starters/embabel-agent-starter-mcpserver/pom.xml
- Severity: medium | Apache Tomcat Denial of Service via invalid HTTP priority header
↪ Recommendation: Upgrade org.apache.tomcat.embed:tomcat-embed-core to a safe version (see advisory below)
↪ Advisory URL: https://github.com/advisories/GHSA-3p2h-wqq4-wf4h
```
Added vulnerability report generation to workflow …
=> Dependabot workflow fixes

README.md
This pull request introduces a minor update to the `README.md` file by adding a badge that indicates the project is profiled with JProfiler. This helps communicate profiling tool usage to contributors and users.
=> Add JProfiler badge to README

embabel-agent-api/pom.xml, embabel-agent-api/src/main/kotlin/com/embabel/agent/config/AgentPlatformProperties.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/config/ContextRepositoryProperties.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/config/ProcessRepositoryProperties.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/config/ToolGroupsConfiguration.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/config/migration/DeprecatedPropertyScanner.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/config/migration/DeprecatedPropertyScanningConfig.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/config/migration/DeprecatedPropertyWarningConfig.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/core/deployment/AgentScanningProperties.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/rag/RagServiceEnhancerProperties.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/spi/support/LlmDataBindingProperties.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/spi/support/LlmOperationsPromptsProperties.kt, embabel-agent-api/src/main/kotlin/com/embabel/agent/testing/integration/AgentPlatformTestExtensions.kt, embabel-agent-api/src/main/kotlin/com/embabel/chat/agent/AgentPlatformChatSession.kt, embabel-agent-autoconfigure/models/embabel-agent-bedrock-autoconfigure/src/main/kotlin/com/embabel/agent/config/models/bedrock/BedrockModels.kt, embabel-agent-autoconfigure/models/embabel-agent-bedrock-autoconfigure/src/main/resources/application-bedrock.yml, embabel-agent-autoconfigure/models/embabel-agent-dockermodels-autoconfigure/src/main/kotlin/com/embabel/agent/config/models/docker/DockerLocalModelsConfig.kt, embabel-agent-discord/pom.xml, embabel-agent-discord/src/main/kotlin/com/embabel/agent/discord/DiscordConfiguration.kt, embabel-agent-rag/embabel-agent-rag-neo/src/main/kotlin/com/embabel/agent/rag/neo/ogm/NeoRagServiceProperties.kt, embabel-agent-rag/pom.xml, embabel-agent-shell/src/main/kotlin/com/embabel/agent/shell/config/ShellProperties.kt, embabel-agent-starters/embabel-agent-starter-shell/pom.xml, embabel-agent-starters/embabel-agent-starter-shell/src/main/java/com/embabel/agent/starter/shell/AgentShellStarterProperties.java
This pr support all @ConfigurationProperties classes auto completion and consolidate / clean-up Configuration Properties.
I greatly appreciate @igordayen`s direction [#845 #899 ] .
The most significant changes involve enhancing annotation processing support in the Maven build and refactoring the class with @ConfigurationProperties annotation.
Added a kapt execution to Maven build  to enable annotation processing, specifically including the spring-boot-configuration-processor for improved Spring Boot configuration metadata generation.
- embabel-agent-api/pom.xml
- embabel-agent-discord/pom.xml
- embabel-agent-rag/pom.xml
In embabel-agent-starter-shell module add  spring-boot-configuration-processor  in pom, because of it Java class, do not need kapt.
1. Refactored the …
=> Support configuration auto completion and consolidate/clean up Configuration Properties

embabel-agent-autoconfigure/models/embabel-agent-bedrock-autoconfigure/src/main/kotlin/com/embabel/agent/config/models/bedrock/BedrockModels.kt
This pull request introduces an update to the `BedrockModels` class to enhance tool-calling capabilities. The main change is the addition of a `ToolCallingManager` to the builder configuration, which improves the integration and observability of tool-calling operations.
Tool-calling integration:
* Added a `ToolCallingManager` to the `BedrockModels` builder, including observation registry configuration for improved monitoring of tool-calling operations.
=> Add ToolCallingManager Observability support

embabel-agent-code/src/test/kotlin/com/embabel/coding/tools/GitReferenceTest.kt
This pull request introduces a minor update to the `GitReferenceTest` class to improve test reliability across operating systems. The test class is now disabled on Windows due to file locking issues with Git pack files.
* Testing reliability:
* [`embabel-agent-code/src/test/kotlin/com/embabel/coding/tools/GitReferenceTest.kt`](diffhunk://#diff-b92a06bbbb1d7026df5e951fa0e12a5ed8696474380c29fdcd2cd2362f1d9879R27-R34): Added the `@DisabledOnOs(OS.WINDOWS, disabledReason = "Windows file locking with Git pack files")` annotation to prevent test failures on Windows environments.
=> Disable GitReferenceTest on Windows due to CI Build Issues.
