embabel-agent-dependencies/pom.xml
embabel-agent-rag/pom.xml
pom.xml

This pull request introduces a new Maven module, `embabel-agent-rag`, and integrates it into the project structure. The changes include adding the module to the parent `pom.xml`, creating its own `pom.xml` file, and listing it as a dependency in the `embabel-agent-dependencies/pom.xml`.
* **Module inclusion in parent POM**: Added `embabel-agent-rag` as a module in the root `pom.xml` to integrate it into the overall project build. (`pom.xml`, [pom.xmlR23](diffhunk://#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R23))
* **New module POM file**: Created a `pom.xml` for `embabel-agent-rag` with dependencies, build plugins, and metadata. This includes a test dependency on `embabel-agent-test` and the use of `kotlin-maven-plugin` and `maven-surefire-plugin`. …

Add embabel-agent-rag module.

---

embabel-agent-api/scripts/mcp_server.cmd
embabel-agent-api/scripts/shell.ps1
embabel-agent-api/scripts/support/check_env.bat
embabel-agent-api/scripts/support/check_env.ps1

This pull request refactors the startup scripts for the `embabel-agent-api` project to centralize environment variable checks and improve maintainability. Key changes include the introduction of shared environment validation scripts and updates to existing batch and PowerShell scripts to use these shared checks.
* Added `check_env.bat` to validate the presence of `OPENAI_API_KEY` and `ANTHROPIC_API_KEY` environment variables, with user-friendly error messages and guidance on obtaining and setting API keys.
* Added `check_env.ps1` to perform the same validation in PowerShell, ensuring consistent behavior across platforms.
* Refactored `mcp_server.cmd` to include a call to `check_env.bat` for environment validation before starting the server.
* Updated `shell.cmd` to replace inline …

Synch up Windows and Mac/Linux startup scripts.

---

embabel-agent-api/scripts/shell_docker.cmd
embabel-agent-api/scripts/shell_docker.ps1

This pull request introduces changes to the Spring profile configurations and adds new scripts for Docker-specific environments. The most important changes include updating the active Spring profiles in existing scripts and adding new scripts with environment checks for Docker environments.
* [`embabel-agent-api/scripts/shell.cmd`](diffhunk://#diff-013696b1a8a589dadb335f9b6401bd2c317f21e690de6683997d0366d4b2ca1fL13-R13): Updated the `SPRING_PROFILES_ACTIVE` environment variable to replace the `starwars` profile with the `severance` profile.
* [`embabel-agent-api/scripts/shell.ps1`](diffhunk://#diff-75b012cbe3adb7f86618ed2205e1d0d2b0bdbd97ebaa6383d8c19da07975c689L19-R19): Updated the `SPRING_PROFILES_ACTIVE` environment variable to replace the `starwars` profile with the `severance` …

Add shell scripts for Windows with dependency on Docker.

---

embabel-agent-api/src/main/kotlin/com/embabel/plan/README.md
embabel-agent-api/src/test/kotlin/com/embabel/agent/api/common/AutonomyActionLeakageTest.kt

Test src:
embabel-agent/embabel-agent-api/src/test/kotlin/com/embabel/agent/api/common/AutonomyActionLeakageTest.kt
README:
embabel-agent/embabel-agent-api/src/main/kotlin/com/embabel/plan/README.md

Agent Leak Detection Test and Planning System Algorithm README

---

embabel-agent-api/src/main/kotlin/com/embabel/agent/config/PostProcessBeansListener.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/spi/support/AutoRegistration.kt

Please refer to Issue writeup:
https://github.com/embabel/embabel-agent/issues/51
Added / Modified files:
new file:   embabel-agent-api/src/main/kotlin/com/embabel/agent/config/PostProcessBeansListener.kt
modified:   embabel-agent-api/src/main/kotlin/com/embabel/agent/spi/support/AutoRegistration.kt

Beanprocessor fixes  with proper Profile(!test)

---

embabel-agent-api/src/main/kotlin/com/embabel/agent/api/common/Autonomy.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/config/AgentPlatformConfiguration.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/spi/support/EventPublishingToolCallback.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/spi/support/MetadataEnrichedToolCallback.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/spi/support/ObservabilityToolCallback.kt

Towards #298. Custom observability around tool usage.

Publish observability events on tool usage

---

embabel-agent-rag/pom.xml
embabel-agent-rag/src/main/kotlin/com/embabel/agent/rag/config/neo/NeoVectorStoreConfiguration.kt

This pull request introduces significant enhancements to the `embabel-agent-rag` project by integrating new dependencies and adding a configuration class for Neo4j-based vector storage. These changes improve the project's ability to handle embeddings and vectorized data efficiently.
* [`embabel-agent-rag/pom.xml`](diffhunk://#diff-948916305efe387d4a5b496dee5aae337348a30063fb4f273b419222bd99431aR16-R28): Added dependencies for `embabel-common-ai`, `spring-ai-vector-store`, and `spring-ai-neo4j-store`. These libraries provide core AI functionalities, vector storage capabilities, and Neo4j integration for the project.
* [`embabel-agent-rag/src/main/kotlin/com/embabel/agent/rag/config/neo/NeoVectorStoreConfiguration.kt`](diffhunk://#diff-6c390af14be672d4244400f4629cea1a203adca2397e20cb5839d65f …

Refactor Neo dependencies out of embabel-agent-api module.

---

embabel-agent-api/pom.xml
embabel-agent-api/src/main/kotlin/com/embabel/agent/api/common/Transformation.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/api/common/support/TransformationAction.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/api/dsl/AgentBuilder.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/rag/Ingester.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/rag/RagResponse.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/rag/RagResponseFormatter.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/rag/support/SpringVectorStoreRagService.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/rag/tools/RagServiceTools.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/tools/file/FileTools.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/tools/file/PatternSearch.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/tools/file/WellKnownFileContentTransformers.kt
embabel-agent-api/src/test/java/com/embabel/agent/rag/SimpleRagRagResponseFormatterTest.kt
embabel-agent-api/src/test/kotlin/com/embabel/agent/tools/file/FileReadToolsTest.kt
embabel-agent-api/src/test/kotlin/com/embabel/agent/tools/file/PatternSearchTest.kt
embabel-agent-api/src/test/kotlin/com/embabel/agent/tools/file/WellKnownFileContentTransformersTest.kt

Add more tests
Polish pattern search
Polishing

Add more tests

---

embabel-agent-api/src/main/kotlin/com/embabel/agent/event/logging/LoggingAgenticEventListener.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/event/logging/personality/colossus/ColossusLoggingAgenticEventListener.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/event/logging/personality/montypython/MontyPythonLoggingAgenticEventListener.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/event/logging/personality/severance/SeveranceLoggingAgenticEventListener.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/event/logging/personality/starwars/StarWarsLoggingAgenticEventListener.kt

Makes subclasses much clearer and less error-prone

Change LoggingAgenticEventListener to use method overrides rather than constructor arguments

---

embabel-agent-api/.embabel/log.jsonl
embabel-agent-api/src/main/kotlin/com/embabel/agent/api/dsl/mapper.kt
embabel-agent-api/src/test/kotlin/com/embabel/agent/api/dsl/MapperParallelTest.kt
embabel-agent-api/src/test/kotlin/com/embabel/agent/api/dsl/MapperTest.kt
embabel-agent-api/src/test/kotlin/com/embabel/agent/api/dsl/ParallelizationTest.kt

Parallel mapping wasn't truly parallelizing.
This fixes that and adds test.

Improve parallel mapping

---

embabel-agent-api/src/main/kotlin/com/embabel/agent/core/AgentPlatform.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/core/AgentProcess.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/core/OperationStatus.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/core/support/AbstractAgentProcess.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/core/support/DefaultAgentPlatform.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/spi/support/InMemoryAgentProcessRepository.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/web/sse/SseController.kt
embabel-agent-api/src/test/kotlin/com/embabel/agent/e2e/AgentPlatformIntegrationTest.kt

- Add SSE support
- Separate process run from process creation to enable async usage
- Fix bug where `AgentProcess` instances were not being persisted to repository

Add SSE support

---

embabel-agent-autoconfigure/src/test/java/com/embabel/agent/config/annotation/LoggingThemeParameterizedTest.java

This pull request includes a small change to the `LoggingThemeParameterizedTest` class. The change renames the class from `EdgeCaseProfileActivationTest` to `LoggingThemeParameterizedTest` to better reflect its purpose.

Clean up LoggingThemeParameterizedTest.java

---

embabel-agent-api/src/main/kotlin/com/embabel/agent/config/models/OpenAiCompatibleModelFactory.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/config/models/OpenAiModels.kt
embabel-agent-api/src/test/kotlin/com/embabel/agent/config/models/OpenAiCompatibleModelFactoryTest.kt

ref: https://github.com/embabel/embabel-agent/issues/589

Support custom OpenAI completions path and embeddings path

---

.idea/jarRepositories.xml
embabel-agent-api/src/main/kotlin/com/embabel/agent/config/models/OpenAiModels.kt
embabel-agent-api/src/test/kotlin/com/embabel/agent/config/models/Gpt5ChatOptionsConverterTest.kt
embabel-agent-api/src/test/kotlin/com/embabel/agent/config/models/optionsConverterTestUtils.kt

Also upgrades version to `0.1.1-SNAPSHOT`

Add GPT-5 support

---

embabel-agent-rag/embabel-agent-rag.iml
embabel-agent-rag/pom.xml
embabel-agent-rag/src/tests/kotlin/com/embabel/agent/rag/Neo4jTestContainer.kt
embabel-agent-rag/src/tests/kotlin/com/embabel/agent/rag/TestNeo4jConfig.kt
embabel-agent-rag/src/tests/kotlin/com/embabel/agent/rag/ogm/OgmCypherSearchTest.kt

Add Neo4j Test Containers 
No stubbed test/reference data as yet. 
One minimal test. 
For better coverage I need to get a better Spring Boot test config. Options to achieve this are: 
a) I will work it out myself
b) We could quickly pair (probably faster, but either way works).

Add Neo4j Test Container

---

embabel-agent-api/src/main/kotlin/com/embabel/agent/core/ProcessOptions.kt
embabel-agent-api/src/test/java/com/embabel/agent/core/ProcessOptionsBuilderTest.java

This commit introduces a builder for ProcessControl, and uses said builder in the ProcessOptions builder.
See #784

Add builder for ProcessControl

---

embabel-agent-api/src/main/kotlin/com/embabel/agent/config/RagServiceConfiguration.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/rag/AbstractWritableContentElementRepository.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/rag/ContextualTool.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/rag/RagService.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/rag/WritableContentElementRepository.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/rag/WritableStore.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/rag/ingestion/Ingester.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/rag/ingestion/MultiIngester.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/rag/support/FacetedRagService.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/rag/support/RagFacet.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/rag/support/SpringVectorStoreRagService.kt
embabel-agent-api/src/test/kotlin/com/embabel/agent/rag/ingestion/MultiIngesterTest.kt
embabel-agent-rag/embabel-agent-rag-lucene/src/main/kotlin/com/embabel/agent/rag/lucene/LuceneRagFacetProvider.kt
embabel-agent-rag/embabel-agent-rag-lucene/src/test/kotlin/com/embabel/agent/rag/lucene/LuceneRagFacetProviderTest.kt
embabel-agent-rag/embabel-agent-rag-neo/src/main/kotlin/com/embabel/agent/rag/neo/ogm/OgmRagFacetProvider.kt
embabel-agent-rag/embabel-agent-rag-neo/src/test/kotlin/com/embabel/test/NeoIntegrationTestSupport.kt

Change RAG to use facets

---

embabel-agent-api/pom.xml
embabel-agent-api/src/main/kotlin/com/embabel/agent/config/AgentPlatformConfiguration.kt
embabel-agent-api/src/main/kotlin/com/embabel/agent/config/models/OllamaModels.kt
embabel-agent-autoconfigure/embabel-agent-platform-autoconfigure/src/main/java/com/embabel/agent/autoconfigure/platform/AgentPlatformAutoConfiguration.java
embabel-agent-autoconfigure/embabel-agent-platform-autoconfigure/src/main/java/com/embabel/agent/autoconfigure/platform/ScanConfiguration.java
embabel-agent-autoconfigure/embabel-agent-platform-autoconfigure/src/main/java/com/embabel/agent/config/annotation/AgentPlatform.java
embabel-agent-autoconfigure/embabel-agent-platform-autoconfigure/src/main/java/com/embabel/agent/config/annotation/EnableAgents.java
embabel-agent-autoconfigure/models/embabel-agent-anthropic-autoconfigure/src/main/java/com/embabel/agent/autoconfigure/models/anthropic/AgentAnthropicAutoConfiguration.java
embabel-agent-autoconfigure/models/embabel-agent-anthropic-autoconfigure/src/main/kotlin/com/embabel/agent/config/models/anthropic/AnthropicModelsConfig.kt
embabel-agent-autoconfigure/models/embabel-agent-ollama-autoconfigure/pom.xml
embabel-agent-autoconfigure/models/embabel-agent-ollama-autoconfigure/src/main/java/com/embabel/agent/autoconfigure/models/ollama/AgentOllamaAutoConfiguration.java
embabel-agent-autoconfigure/models/embabel-agent-ollama-autoconfigure/src/main/kotlin/com/embabel/agent/config/models/ollama/OllamaModelsConfig.kt
embabel-agent-autoconfigure/models/embabel-agent-ollama-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
embabel-agent-autoconfigure/models/embabel-agent-ollama-autoconfigure/src/test/kotlin/com/embabel/agent/config/models/ollama/OllamaOptionsConverterTest.kt
embabel-agent-autoconfigure/models/embabel-agent-openai-autoconfigure/src/main/java/com/embabel/agent/autoconfigure/models/openai/AgentOpenAiAutoConfiguration.java
embabel-agent-autoconfigure/pom.xml
embabel-agent-dependencies/pom.xml
embabel-agent-starters/embabel-agent-starter-anthropic/pom.xml
embabel-agent-starters/embabel-agent-starter-ollama/pom.xml
embabel-agent-starters/embabel-agent-starter-openai/pom.xml
embabel-agent-starters/pom.xml

This pull request introduces significant improvements to the modularity, clarity, and flexibility of the agent platform's model configuration and autoconfiguration system. The changes decouple Ollama model support into its own autoconfiguration module, simplify model registration, and enhance Spring Boot integration for easier extension and maintenance. Deprecated annotations and properties are also marked for removal, and configuration scanning is now more explicit and maintainable.
**Autoconfiguration and Component Scanning Improvements:**
* Introduced a new `ScanConfiguration` class to explicitly handle `@ComponentScan` and `@ConfigurationPropertiesScan` for the `com.embabel.agent` package, improving clarity and maintainability of component scanning. …

Ollama Autoconfiguration Framework Modularity Improvements.

---

pom.xml

This pull request updates the version of the `embabel-common` dependency in the `pom.xml` file. The version is incremented from `0.1.3` to `0.1.4-SNAPSHOT` to reflect ongoing development.
* Updated the `embabel-common.version` property in `pom.xml` from `0.1.3` to `0.1.4-SNAPSHOT` to use the latest snapshot version for development.

Update to latest embabel-common development verion.

---

embabel-agent-autoconfigure/models/embabel-agent-anthropic-autoconfigure/src/main/kotlin/com/embabel/agent/config/models/anthropic/AnthropicModelsConfig.kt

This pull request updates the Anthropic model configuration to improve observability and monitoring by integrating the `ObservationRegistry` throughout the API client and tool calling setup. These changes ensure that relevant metrics and traces are captured for Anthropic model interactions.
* Injected `ObservationRegistry` as a dependency into the `AnthropicModelsConfig` class to enable metric and trace collection.
* Passed the `ObservationRegistry` to the `ToolCallingManager` and directly to the Anthropic chat model builder, allowing for comprehensive monitoring of tool calls and model usage.
* Configured both the `RestClient` and `WebClient` builders with the `ObservationRegistry`, ensuring all HTTP client interactions are observable.
* Added necessary imports for `ObservationRegistry`, …

Add Observability capability to Anthropic LLM(s)

---

embabel-agent-autoconfigure/models/embabel-agent-ollama-autoconfigure/src/main/kotlin/com/embabel/agent/config/models/ollama/OllamaModelsConfig.kt

This pull request updates the Ollama model configuration to improve observability and tool integration. The main changes involve injecting an `ObservationRegistry` for enhanced monitoring and wiring up a `ToolCallingManager` to support tool usage with Ollama models.
**Observability and Monitoring Enhancements:**
* Added an `ObjectProvider<ObservationRegistry>` as a constructor parameter to `OllamaModelsConfig`, allowing flexible injection of an observation registry for metrics and tracing.
* Updated the construction of `RestClient` and `WebClient` in the Ollama API to use the provided `ObservationRegistry` for improved request monitoring. [[1]](diffhunk://#diff-1d2812b67733da7db801ceb2c239402027be49a7fa21afb4119f5dd6e0e471d4R141-R157) …

Add Observability support for Ollama LLM(s)

---

embabel-agent-autoconfigure/models/embabel-agent-deepseek-autoconfigure/src/main/kotlin/com/embabel/agent/config/models/deepseek/DeepSeekModelsConfig.kt

This pull request updates the `DeepSeekModelsConfig` class to improve observability and tool integration for DeepSeek model configuration. The most important changes are grouped below:
**Observability Enhancements:**
* Injected an `ObjectProvider<ObservationRegistry>` into the `DeepSeekModelsConfig` constructor to enable flexible access to the observation registry for metrics and tracing.
* Configured the `DeepSeekChatModel` and its `ToolCallingManager` to use the observation registry, defaulting to `ObservationRegistry.NOOP` if none is available.
* Updated both `RestClient` and `WebClient` builders to use the observation registry, ensuring consistent observability across HTTP clients.
**Tool Integration:**
* Added a `ToolCallingManager` to the `DeepSeekChatModel` configuration, enabling …

Add Observability to DeepSeek LLM(s)

---

README.md

Added badges for YourKit and JProfiler to README.

Add profiling badges for YourKit and JProfiler
